### ISSUE TITLE
Button disappears

### ISSUE THREAD

**Issue by liuzhi123hao** [TheIllusiveC4/Polymorph#160] opened 2022-04-01 05:46 UTC
And this together with the button will disappear one button backpack organization Next
Links：https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next

**Comment by TheIllusiveC4** [comment] 2022-04-01 06:44
Can you please fill out the bug report with the version numbers and reproduction steps? I'll need to know this information so that I can see what you're talking about and replicate it on my end.

**Comment by liuzhi123hao** [comment] 2022-04-10 02:24
Stand-alone works fine, online the server is also installed but there is no button on the interface

**Comment by EldrinFal** [comment] 2022-04-18 21:33
I'm having this issue as well.  Using MC 18.1.  I tried with the last mod version that states it's for 18.1 and also the latest mod.  Basically in the crafting screen when I select the item to craft, the polymorph button briefly appears, then it's gone.  I have a lot of mods so I assume it's a conflict of some kind.  Would a log help?

**Comment by TheIllusiveC4** [comment] 2022-04-19 04:52
A log might help, but mostly you'd have to figure out which mod exactly is causing it. Do a binary search by taking half of the mods out, then testing again. If it happens again, take another half out and repeat. If it doesn't happen, then test with the half that you removed and repeat. Keep removing mods this way until you find the culprit.

**Comment by EldrinFal** [comment] 2022-04-19 05:45
[debug.log](https://github.com/TheIllusiveC4/Polymorph/files/8510150/debug.log)
[latest.log](https://github.com/TheIllusiveC4/Polymorph/files/8510151/latest.log)

Ok, well let's start with the logs since I can readily provide those.  Considering I have something like 170 mods, it will take some time to narrow it down.  At quick glance, I did notice in the debug log that there are some lines about the class version was too high for what the mod supports.  I'm no programmer, so not sure if that is relevant.  I have JAVA 18.

**Comment by TheIllusiveC4** [comment] 2022-04-19 06:59
Hmm, well I don't see anything wrong in the logs and I don't think this would be caused by a mismatched Java version so I'll have to wait until you can narrow down which mod might be causing the issue.

**Comment by EldrinFal** [comment] 2022-04-21 05:10
I was able to pinpoint the problematic mod to one called "Technical Enchant +" found on Planetminecraft.  It's a Datapack which kept it a bit under my radar initially.  I was using ver 5.6 and after removing and adding it twice, I am certain that it was causing the conflict.  That being said, there was a version 5.7 released a week ago and that one seems to have resolved the problem.  Not sure if you want to look at the mod to avoid the issue possibly popping up again.  If so, here is the link to that page:

https://www.planetminecraft.com/data-pack/technical-enchant-for-1-17/

(It says 1.17 but the page itself says it is also for 1.18)

**Comment by TheIllusiveC4** [comment] 2022-04-21 20:58
It seems like they've updated to 6.0 now and I cannot find any links to old versions so I cannot test the problematic 5.6 version.

But anyways, I'll close this issue since your problem has been resolved and OP has not provided the necessary details for theirs.

**Closed as completed by TheIllusiveC4** 2022-04-21 20:58 UTC
Labels: type: bug

**Comment by LiviiYS** [comment] 2022-05-06 16:07
I have been having the same issue & for me the issue comes from the mod extra origins

https://www.curseforge.com/minecraft/mc-mods/extra-origins
