### ISSUE TITLE
wont stay on seleted item

### ISSUE THREAD

**Issue by FullMetalMaster** [TheIllusiveC4/Polymorph#65] opened 2021-02-21 07:22 UTC
forge

keeps spaming back and forth between items of the same recipe seems to happened with alot of mods

**Comment by TheIllusiveC4** [comment] 2021-02-21 07:52
Please be more specific and follow the bug report template.

1) What version of Polymorph are you using?
2) What version of Forge are you using?
3) Can you reproduce this with only Polymorph installed?
4) If you can't reproduce this with only Polymorph installed, what are the minimum number of mods installed needed to reproduce this issue (and what are they)?
5) Please provide steps to reproduce the issue.

**Comment by FullMetalMaster** [comment] 2021-02-21 08:12
seems to specifically happen with improve stations https://www.curseforge.com/minecraft/mc-mods/improved-stations-forge

**Comment by FullMetalMaster** [comment] 2021-02-21 08:13
and the Polymorph mod

**Comment by FullMetalMaster** [comment] 2021-02-21 08:13
and the Polymorph mod

**Comment by TheIllusiveC4** [comment] 2021-02-21 08:46
Okay, then I'm closing this issue as it's a duplicate of https://github.com/TheIllusiveC4/Polymorph/issues/61. I'll be providing updates there once I have developed a solution.

**Closed as completed by TheIllusiveC4** 2021-02-21 08:46 UTC
Labels: type: bug
