### ISSUE TITLE
[BUG]Toms Storage isnt supported

### ISSUE THREAD

**Issue by f0kx** [TheIllusiveC4/Polymorph#224] opened 2023-06-30 21:54 UTC
Versions :
* Polymorph: 46.2+1.19.2
* Forge: 43.2.11
Observed Behavior: When i want to craft specific stuff what have same input but different output inside Toms Storage there is no button for Polymorph
Expected Behavior: There should be a button to change recipe

**Comment by TheIllusiveC4** [comment] 2023-06-30 22:28
Duplicate of https://github.com/illusivesoulworks/polymorph/issues/203
This compatibility doesn't exist yet in 1.19.2.

**Closed as not planned by TheIllusiveC4** 2023-06-30 22:28 UTC
Labels: duplicate

**Comment by f0kx** [comment] 2023-06-30 22:29
so you need to clear it on your startpage because you said it :P but thx anyway

**Comment by TheIllusiveC4** [comment] 2023-06-30 22:39
I do. It says on the CurseForge project page:

> Note for 1.19.x: Many of these integrations have not been implemented yet on 1.19.x.

Although I just realized I am missing this on Modrinth so I'll update it there also.
