### ISSUE TITLE
[1.16.5] Dedicated server hard lock and recovery - in relation to Ae2 autocrafting

### ISSUE THREAD

**Issue by ProsperCraft** [TheIllusiveC4/Polymorph#114] opened 2021-12-03 22:33 UTC
When we started working on AE2 autocrafting, we started getting hard locks that would last 5-10 minutes then the server would recover, this is a warmroast profile I ran showing polymorph while it was locked.

#### Versions (Be specific, do not write "latest"):
* Polymorph: polymorph-forge-1.16.5-0.33
* Forge/Fabric: forge-1.16.5-36.2.19
* appliedenergistics2-8.4.4

#### Steps to Reproduce:
shift clicking any pattern in pattern terminal of AE2 does it
 or trying to clear a recipe in pattern terminal.
...

Warmroast-
![image](https://user-images.githubusercontent.com/4427684/144676503-fa0f84be-390a-410a-86b0-02644ffc4bff.png
Included zip of the web page if you need more data then the screenshot shows.
[polymorph.zip](https://github.com/TheIllusiveC4/Polymorph/files/7652593/polymorph.zip)
)

**Comment by TheIllusiveC4** [comment] 2021-12-11 07:16
I am unable to reproduce this issue on a dedicated server. I do not experience any lock-ups with using the AE2 pattern terminal as you described.

I attempted to make a guess at a possible cause and implement a tentative fix. Can you use this snapshot build and tell me if it fixes the issue on your server?
[polymorph-forge-1.16.5-0.34-SNAPSHOT20211210.zip](https://github.com/TheIllusiveC4/Polymorph/files/7696600/polymorph-forge-1.16.5-0.34-SNAPSHOT20211210.zip)

**Comment by FoxMcloud5655** [comment] 2021-12-14 16:01
The issue isn't that the server crashes, it's that the server freezes for a long time.  Here's a link to the relevant discussion on AE2's issues page: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/5752

**Comment by TheIllusiveC4** [comment] 2021-12-14 19:28
I never mentioned it crashing, I understand that it's a freeze. I still cannot reproduce that behavior in any way. Regardless, I'll need someone that _is_ experiencing the issue to test the snapshot build I attached in my previous comment and confirm whether or not that fixes the problem.

**Comment by FoxMcloud5655** [comment] 2021-12-14 22:52
I was just making sure that it was clerified that the server doesn't actually crash from this; wasn't trying to correct you or anything.  Sorry if it came off that way.

I will test the snapshot build you posted as soon as I am able to.  I did notice (I think, I played for 30 minutes) that disabling the AE2 integration only on the server does fix this, but whether it's because the client receives the config of the server or simply that the server doesn't process something, I am unsure of.

**Comment by TheIllusiveC4** [comment] 2021-12-14 23:00
> I was just making sure that it was clerified that the server doesn't actually crash from this; wasn't trying to correct you or anything. Sorry if it came off that way.

It's quite alright, no need for apologies. Similarly, I was also just clarifying that I understood it was not a crashing issue and I apologize if that came off as me being defensive.

>  I did notice (I think, I played for 30 minutes) that disabling the AE2 integration only on the server does fix this, but whether it's because the client receives the config of the server or simply that the server doesn't process something, I am unsure of.

That seems right. The way the integration is coded means that the server wouldn't process anything coming from the client, which I think is where the source of the issue comes from initially.

**Comment by Darkere** [comment] 2021-12-15 16:08
I can confirm a similar issue also happens from RS's integration.

Was able to run spark while it was frozen. See server thread. 
https://spark.lucko.me/KHuSv2JuXz

During this profile I was not more than maybe 3 chunks away from the only RS system nearby. So I'm not sure why it gets stuck loading the chunk.

One of many crash reports we've received from users:

[crash-reports_crash-2021-12-15_06.18.56-server.txt](https://github.com/TheIllusiveC4/Polymorph/files/7720935/crash-reports_crash-2021-12-15_06.18.56-server.txt)

**Comment by TheIllusiveC4** [comment] 2021-12-15 23:26
For the RS issue, I think I know what's wrong and I have a fix in-dev. I'm waiting for someone to follow-up on this issue and confirm or deny the snapshot build above fixes the AE2 issue before releasing an update, but if it takes much longer then I'll just release an update with the RS fix.

**Comment by ProsperCraft** [comment] 2021-12-15 23:39
Publish and then we will test, we run a large server with players using the curseforge launcher,  it is easier to test a published mod then downing the server for everyone, putting it on the client and server and trying to reproduce it.

**Comment by ProsperCraft** [comment] 2021-12-15 23:40
I wonder what the poster on the AE2 issue meant by they got polymorph to not interact with AE2, is there a config option?

**Comment by FoxMcloud5655** [comment] 2021-12-15 23:55
Yes, there is a config option.  I still have yet to test the snapshot due to me being sick and not playing on my computer much.  Sorry for the wait.

**Comment by TheIllusiveC4** [comment] 2021-12-16 00:09
> Publish and then we will test, we run a large server with players using the curseforge launcher, it is easier to test a published mod then downing the server for everyone, putting it on the client and server and trying to reproduce it.

I'm wary of publishing code changes without verifying that it actually does anything, but in the interest of progress I've gone ahead and released the latest update that is meant to address this and other issues. Please let me know if this issue has been addressed or continues to be a problem.

> I wonder what the poster on the AE2 issue meant by they got polymorph to not interact with AE2, is there a config option?

Polymorph has a config file in the `configs` folder called `polymorph-integrations.toml`. Setting any of the modules to `false` will turn off every interaction Polymorph does with it. This is primarily meant to be used in instances where there are problems with the integration of a specific mod, such as what's illustrated by this exact issue.

**Comment by TainanRezende** [comment] 2021-12-16 02:24
the update that soutaram solving this problem didn't help the problem, I'm going through the same problem as the one reported in this topic

**Comment by TheIllusiveC4** [comment] 2021-12-16 04:21
So using Polymorph 0.34+ does not fix this issue for you?

Can someone list out some detailed reproduction steps? I'm not really sure why I am unable to reproduce this despite the fact that multiple people are experiencing this.

**Comment by TheIllusiveC4** [comment] 2021-12-16 09:01
Alright, second attempt at this. Everyone try out 1.16.5-0.36 and let me know if the issue persists.

**Comment by FoxMcloud5655** [comment] 2021-12-16 10:38
From all of what I've seen, it's a lag issue due to having a massive number of types of items in your ME System.

**Comment by TainanRezende** [comment] 2021-12-16 12:29
> Tudo bem, segunda tentativa. Todos experimentam 1.16.5-0.36 e me avisem se o problema persistir.

so this bug/problem is intermittent and occurs after having many items and recipes in the applied system and when there are more people on the server or it can occur when there is only one, it is very fickle but it happens I re-added your mod again to test it because I had taken because i couldn't play and i'm testing until agra apparently resolvable but if dnv happens i immediately run here to talk, if you want to talk to me my friends or enter the server that was happening this is my id in discord TainanRezende#2748

**Comment by starmun-0010** [comment] 2021-12-20 11:05
Experiencing a similar issue in starpack titan because of the interaction between Polymorph and Refined storage.
I have only been able to reproduce on the server world and not on the client only local world.
**Polymorph Versions Tested**
0.33, 0.36

Steps to reproduce on starpacks server.

1. Refined storage system should have dozens of items in it.
2. Leave a recipe to be crafted inside the crafting grid from Refined storage. (see image for an example)
![unknown](https://user-images.githubusercontent.com/5557278/146757394-29b7c9b0-535e-46ab-b40b-c8d210828dd9.png)
3. Make sure that the server saves the game.
4. Restart the server.
5. Server will refuse to properly boot up and will freeze indefinitely or until the server watchdog kills it.

**Crash Report**
[crash-2021-12-17_06.11.04-server.txt](https://github.com/TheIllusiveC4/Polymorph/files/7744789/crash-2021-12-17_06.11.04-server.txt)

**Comment by TheIllusiveC4** [comment] 2021-12-20 15:14
@starmun-0010 Do you have a crash log for the test instance with Polymorph 0.36? The one you've attached has version 0.33, which doesn't have the fix I recently implemented so that's not of much relevance unfortunately.

**Comment by starmun-0010** [comment] 2021-12-20 17:44
Yes, crash-log with 0.36. Seems like the same stack trace..
[crash-2021-12-17_18.20.48-server.txt](https://github.com/TheIllusiveC4/Polymorph/files/7747058/crash-2021-12-17_18.20.48-server.txt)

**Comment by TheIllusiveC4** [comment] 2021-12-21 04:26
I'm working on the RS issue again and may have another possible solution. But while the issue has similar symptoms, the cause is entirely unrelated to this AE2 issue. I'd like to move any further discussion about the RS issue to a new thread I opened specifically for it: https://github.com/TheIllusiveC4/Polymorph/issues/120

And as for this issue with AE2, is anyone able to verify whether or not this issue still occurs with 0.36+?

**Comment by FoxMcloud5655** [comment] 2021-12-21 06:57
I have tested this extensively today, and I can't get the issue to occur no matter what I do.  I think it's safe to close this.  Thank you for your help!

**Comment by TheIllusiveC4** [comment] 2021-12-21 07:38
Alright, great! Thank you for the confirmation, I'll go ahead and consider this resolved until someone says otherwise.

**Closed as completed by TheIllusiveC4** 2021-12-21 07:38 UTC
Labels: type: bug
