### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Kliciou** [TheIllusiveC4/Polymorph#232] opened 2023-08-23 23:07 UTC
### Minecraft Version

1.20.1

### What happened?

I download this with ATM 9. I haven't added or removed any mods from that pack. For whatever reason the button to switch between outputs doesn't appear and I can't see any way to activate it. I have double checked that this is the most current version that I'm running as well.

### How do you trigger this bug?

1. Happens when I try to craft something with multiple recipe outputs.
2. No button appears to switch output
3.
...

### Loader

Forge

### Loader Version

Forge 47.1.3

### API Version

N/A

### Mod Version

Polymorph 0.49.1+1.20.1

**Comment by TheIllusiveC4** [comment] 2024-03-28 01:27
This may be a duplicate of https://github.com/illusivesoulworks/polymorph/issues/234.
If you had any of the Fast suite of mods installed, then the latest version of Polymorph has fixed this issue.

**Closed as not planned by TheIllusiveC4** 2024-03-28 01:27 UTC
Labels: type: bug, duplicate
