### ISSUE TITLE
[1.16.4] dedicated server can't loading

### ISSUE THREAD

**Issue by ptk2003** [TheIllusiveC4/Polymorph#39] opened 2020-11-28 08:03 UTC
Failure message: Polymorph (polymorph) encountered an error during the common_setup event phase
java.lang.RuntimeException: Attempted to load class net/minecraft/client/world/ClientWorld for invalid dist DEDICATED_SERVER

polymorph-forge-1.16.4-0.17
forge-1.16.4-35.1.0

[crash-2020-11-27_19.21.24-fml.txt](https://github.com/TheIllusiveC4/Polymorph/files/5610235/crash-2020-11-27_19.21.24-fml.txt)

**Comment by TheIllusiveC4** [comment] 2020-11-28 08:11
Duplicate of https://github.com/TheIllusiveC4/Polymorph/issues/38
Update Polymorph.

**Closed as completed by TheIllusiveC4** 2020-11-28 08:11 UTC
Labels: type: bug
