### ISSUE TITLE
Incompatibility with Apotheosis gems at smithing table

### ISSUE THREAD

**Issue by NostalJay** [TheIllusiveC4/Polymorph#205] opened 2023-02-18 03:19 UTC
* Polymorph:0.46.1+1.19.2
* Forge/Fabric:43.2.3
* Apotheosis:6.0.3
#### Steps to Reproduce:
1.Install polymorph and apotheosis
2.acquire any gem from apotheosis, and any item with available gem slots.
3.Attempt to combine the item (left slot) and gem (right slot) at the smithing table

To help you identify this issue if unfamiliar with apotheosis, the following commands will come in handy
/apoth lootify ancient      This command will turn the piece of gear in hand into a tier that should have gem slots
/apoth gem random         This command will provide you with a gem, as these cannot be grabbed from jei etc

https://user-images.githubusercontent.com/124755074/219828987-629ab5de-80bc-4c85-8bdc-6d49e7ae2915.mp4

**Comment by NostalJay** [comment] 2023-02-18 03:28
Alternatively, sometimes the correct result will display, as well as a polymorph option to create a previously combined item .  I have not been able to determine what causes which issue, but it appears to be world dependant
![2023-02-17_20 28 10](https://user-images.githubusercontent.com/124755074/219829309-74ca9cf0-7787-4738-80e0-355b105600b5.png)

**Comment by zerotheliger** [comment] 2023-03-14 02:28
can confirm was having similar issues. is there a config im missing somewhere to disable the smithing table over ride? removing the mod fixes the issue on my server.

**Comment by TheIllusiveC4** [comment] 2023-06-29 06:20
Duplicate of https://github.com/illusivesoulworks/polymorph/issues/181

> is there a config im missing somewhere to disable the smithing table over ride?

There isn't but I'll look into adding it as a feature.

**Closed as not planned by TheIllusiveC4** 2023-06-29 06:20 UTC
Labels: type: bug
