### ISSUE TITLE
load error

### ISSUE THREAD

**Issue by christomite** [TheIllusiveC4/Polymorph#9] opened 2020-06-23 21:41 UTC
when the game loads i get this error
![Screenshot (18)](https://user-images.githubusercontent.com/63010657/85466876-1c100d00-b570-11ea-93ed-3cb9021f7240.png)

edit: i did a little research and found its a problem with simple storage.

**Comment by TheIllusiveC4** [comment] 2020-06-24 01:00
> edit: i did a little research and found its a problem with simple storage.

So can I close this issue, or is it still a problem? As for my testing, I'm unable to reproduce this and the game loads fine for me with Simple Storage Network.

**Comment by christomite** [comment] 2020-06-25 21:11
i dont know if its still an issue i just removed the simple storage mod since i rarely used it anyway

**Closed** 2020-06-25 21:48 UTC
Labels: bug
