### ISSUE TITLE
Overlapping buttons when using Charm's portable crafting

### ISSUE THREAD

**Issue by Slugstur** [TheIllusiveC4/Polymorph#179] opened 2022-08-12 18:27 UTC
![image](https://user-images.githubusercontent.com/96501456/184420819-fdeb3f4f-9f06-4745-9c53-a6e9810b61e3.png)

Button overlaps with the crafting recipes book when opening the portable crafting from Charm.
Would be nice if they didn't overlap. Besides the polymorph button usually is right above the 'result square'.

**Comment by TheIllusiveC4** [comment] 2022-10-21 05:47
I cannot reproduce this problem, when using the Portable Crafting from Charm the button appears above the result slot as it's intended. I can see you have other mods installed, please reproduce this with only Charm and Polymorph in order to isolate any other mod incompatibilities. If this problem still occurs, then please list the Charm, Polymorph, and Forge/Fabric versions and a detailed list of instructions to reproduce the issue.

**Comment by MoonliteDelight** [comment] 2023-02-26 02:27
@TheIllusiveC4 I have an answer for this because I've been running into the same issue with a modpack (and it's even more annoying when you have REI/JEI installed bc the recipe picker can get shoved to the _far_ right and into the REI/JEI GUI with method 2 below). It's not a conflict between _just_ Charm and Polymorph. It happens when you have Charm, Polymorph, AND Crafting Tweaks installed. This is because Crafting Tweeks moves the book over to the right side of the GUI and the Portable Crafting GUI moves the Polymorph icon to the right just enough to make the overlap.

Mods/Versions:
Minecraft 1.19.2
Fabric - 0.14.14
Balm (Fabric Edition) - 4.5.2
Charm - 4.4.4
Cloth Config API (Fabric/Forge) - 8.2.88-fabric
Crafting Tweaks (Fabric Edition) - 15.1.0
Fabric API - 0.75.1
Polymorph (Fabric) - 0.46.1

Replication instructions:
Set up - You will need a conflicting recipe. I assume you already have something in your testing kit, but if not, I used a datapack with a single recipe in it to create a conflict (stripped oak wood > spruce stairs). You can quickly create a pack for this with https://crafting.thedestruc7i0n.ca/. 

Two ways of getting a weird overlay:
Method 1 - Crafting book starts closed.
1. Get a vanilla crafting table in your inventory and make sure the crafting book is closed in the inventory. Click the Charm Crafting icon to open the Portable Crafting GUI.
2. Put in the conflicting recipe. You will see this:
![image](https://user-images.githubusercontent.com/64285987/221388706-e7bc86da-6044-4724-a744-d3804c770fe3.png)
3. Bonus: upon clicking the Polymorph icon, the book is opened and the recipe picker is put in a weird spot:
![image](https://user-images.githubusercontent.com/64285987/221388722-6e7f4c83-df01-46d4-9e83-56312c86e0e3.png)

Method 2 - Crafting book starts open.
1. Get a vanilla crafting table in your inventory and make sure the crafting book is open in the inventory. Click the Charm Crafting icon to open the Portable Crafting GUI.
2. Put in the conflicting recipe. You will see this:
![image](https://user-images.githubusercontent.com/64285987/221388767-0502f529-427b-4a32-a6ff-68cb0fb1cb91.png)
3. Bonus: upon clicking the Polymorph icon, the book is closed and the recipe picker is put in a weird spot:
![image](https://user-images.githubusercontent.com/64285987/221388780-232ecc6d-d7cd-4c48-a1ef-adeac58ea5a7.png)

I got this replication with a fresh instance in Curseforge and only these three mods + their dependencies (everything's listed). I'm not entirely sure if this would be something to be fixed on the Polymorph side or the Crafting Tweaks side, since each mod works fine individually with the portable crafting table.

**Closed as completed** 2023-06-30 21:31 UTC
Labels: type: bug, status: confirmed
