### ISSUE TITLE
Polymorph causes a crash with Hexerei mod

### ISSUE THREAD

**Issue by zachsai** [TheIllusiveC4/Polymorph#125] opened 2021-12-29 22:17 UTC
#### Versions (Be specific, do not write "latest"):
* Polymorph: 0.33
* Forge/Fabric: 39.0.9
Polymorph causes a crash with Hexerei mod
The dev of Hexerei thinks its because polymorph doesnt know how to handle his custom recipes
https://pastebin.com/hY6ve73R

**Comment by TheIllusiveC4** [comment] 2022-01-01 04:10
Duplicate of https://github.com/TheIllusiveC4/Polymorph/issues/122

**Closed as completed by TheIllusiveC4** 2022-01-01 04:10 UTC
Labels: type: bug, duplicate
