### ISSUE TITLE
Crash with `appliedenergistics2`

### ISSUE THREAD

**Issue by XyLyXyRR** [TheIllusiveC4/Polymorph#98] opened 2021-10-08 12:26 UTC
#### Versions (Be specific, do not write "latest"):
* Polymorph: 0.0.13-1.16.5
* Forge/Fabric: 0.34.7+1.16
* Applied Energistics: 2 8.3.0-alpha.3
* Minecraft: 1.16.5
#### Steps to Reproduce:
1. Add `Polymorph` `Applied Energistics` to `mods`
2. Launch game and try open inventory
3. Game crashed

Crash Log: [log](https://gist.github.com/XyLyXyRR/bf387159baf3808ed8c41022c808b673)

**Comment by TheIllusiveC4** [comment] 2021-10-08 17:11
Duplicate of https://github.com/TheIllusiveC4/Polymorph/issues/90
Update to the latest Applied Energistics 2 version (8.4.0-alpha.2)

**Closed as completed by TheIllusiveC4** 2021-10-08 17:11 UTC
Labels: type: bug
