### ISSUE TITLE
[1.18.2] Polymorph button disappeared out of nowhere

### ISSUE THREAD

**Issue by championhestu** [TheIllusiveC4/Polymorph#200] opened 2022-12-13 15:20 UTC
#### Versions:
* Polymorph: 1.18.2-0.46
* Forge/Fabric: Forge
#### Observed Behavior:
The Polymorph button has disappeared, no longer allowing me to choose between recipe outcomes.
#### Expected Behavior:
The Polymorph button should appear as usual.
#### Steps to Reproduce:
1. I've restarted Minecraft a dozen times, each time without one of the mods I use.
2. Each time, the button didn't reappear.
3. I redownloaded Polymorph itself, but this yielded no results either.

#### Crash Log:
None.

**Comment by championhestu** [comment] 2022-12-23 18:21
Bumping this.

**Comment by TheIllusiveC4** [comment] 2022-12-23 23:16
Which recipe conflict are you testing it with when it doesn't work? Have you tried testing this with only the mods required for that recipe conflict + Polymorph? This sounds like it could be a mod conflict so you should see if you can test this with a minimal number of mods present.

**Comment by championhestu** [comment] 2022-12-24 01:20
> Which recipe conflict are you testing it with when it doesn't work? Have you tried testing this with only the mods required for that recipe conflict + Polymorph? This sounds like it could be a mod conflict so you should see if you can test this with a minimal number of mods present.

Yes, I have, and it still didn't work. I didn't download any new mods inbetween the time when Polymorph was still working and the time when Polymorph stopped working, so I don't know if it's a mod conflict issue. They were working fine together previously. I've tried a minimal amount of mods together several times, using several different mod combinations (Quark + Farmer's Delight, Vanilla Extension + Nourished Nether, Supplementaries + Decorative Blocks), and Polymorph never worked once. If it's a mod conflict issue, Polymorph should in theory work when I only have 2-3 quality mods downloaded, but it never works.

**Comment by TheIllusiveC4** [comment] 2022-12-24 03:50
Please give me a reproducible instance that I can replicate on my end. Give me the mod versions for each, your Forge version, and which recipe you are attempting, and in what crafting station. For instance, if you choose Quark + Farmer's Delight, then I would need the version of Quark, version of Farmer's Delight, and all the other information I listed.

**Comment by championhestu** [comment] 2022-12-24 15:21
> Please give me a reproducible instance that I can replicate on my end. Give me the mod versions for each, your Forge version, and which recipe you are attempting, and in what crafting station. For instance, if you choose Quark + Farmer's Delight, then I would need the version of Quark, version of Farmer's Delight, and all the other information I listed.

I'll give you several, so you can test out multiple.
**Forge:** 1.18.2-40.1.68
**Quark:** 3.2-358 (+ **AutoRegLib:** 1.7-53) & **Farmer's Delight:** 1.18.2-1.2.0; potato crate, carrot crate, beetroot crate.
**Supplementaries:** 1.18.2-1.5.14 (+ **Selene:** 1.18.2-1.17.9) & **Decorative Blocks:** 1.18.2-2.1.0; wattle frame & lattice.
**Nourished Nether:** 1.18.2-v17 & **Vanilla Extension:** 1.18.2-1.1.2; smooth basalt stairs, slab, wall.
**Vanilla Extension:** & **Comforts:** 1.18.2-5.0.0.4; wool slab (any) & sleeping bag (any).

All are done with the regular crafting table.

**Comment by aleahkarr** [comment] 2022-12-28 01:38
I am having the same issue, even with recipes I was able to craft before. Have you had any luck?

**Comment by itsdinkd** [comment] 2023-01-05 00:27
This has been happening to me on fabric for months now on 1.18.2 in AQM2. Players had to use Improved Station tables to get polymorph to actually show

**Comment by championhestu** [comment] 2023-01-13 20:06
Bump.

**Comment by fuzzyweapon** [comment] 2023-04-17 18:34
Also experiencing this on 1.19.2 Fabric...and I use Supplementaries and Farmers Delight in my pack (but don't use Quark or Nourished Nether).

**Comment by fuzzyweapon** [comment] 2023-04-17 18:36
I have not been using any special stations/crafters and it happened (Note that I was using JEI, but not sure if it was triggered by autoloading the recipe into a crafting grid).  I will keep my eye out if I can somehow get it to revert to working.

**Comment by TheIllusiveC4** [comment] 2023-06-30 10:17
Sorry for the delay on this. In the end, even using the information provided above, I was not able to reproduce any issues with the vanilla crafting table. I was always able to get the Polymorph button to appear for the recipe conflicts mentioned.

However, I have pushed out an update that includes many bug fixes for other issues and this may have been related to one of them. Since it has been some time since the original issue opened, I am closing this simply due to age. If you had issues before, please try the latest update released today. And then if you are still experiencing issues, please open up a new issue report and reference back to this one if appropriate.

**Closed as completed by TheIllusiveC4** 2023-06-30 10:17 UTC
Labels: type: bug
