### ISSUE TITLE
Current update crashes modpack

### ISSUE THREAD

**Issue by Heroncustom** [TheIllusiveC4/Polymorph#147] opened 2022-02-08 01:02 UTC
#### Versions (Be specific, do not write "latest"):
* Polymorph: polymorph-forge-1.18.1-0.37.jar
* Forge/Fabric: Forge 39.0.66
#### Steps to Reproduce:
1. Reloaded without the last three updated mods. elimination brought me to polymorph
2. reloaded with polymorph disabled, no crash
3. reloaded with polymorph enabled, crash.
...

Crash Log: Please use a paste site like [hastebin](https://hastebin.com/).

Im not getting a crash log only exit code 0.

**Comment by TheIllusiveC4** [comment] 2022-02-08 03:20
No crash log? There's nothing that gets generated in your `crash-reports` folder?

If there isn't, there's not much for me to go on. The only thing that got updated was the Sophisticated Backpacks compatibility, so make sure that mod is updated as well (although that wouldn't result in a crash, but it's the only thing it could be).

**Comment by Heroncustom** [comment] 2022-02-08 03:52
Ye the no crash log kinda bugs me. First time compiling a pack and its not
the first time its happened.
No worries. honestly was just trying to bring it to your attention.
Ill check Sop backpacks as it is installed too.
thanks for the response, love your work!

**Comment by Heroncustom** [comment] 2022-02-09 01:53
Just wanted to update you in case it helps.
updated to forge 39.0.75 and it still won't load with Polymorph enabled.
i tried un installing it and reinstalling, same issue.

now im getting a different exit code, but still no crash report.........

im attaching two screenshots.  Its mentioning configs but the one
screenshot is my current untouched config for
polymorph.

Honestly Im not trying to bug you for help, just trying to help solve the
issue.
i dunno how many others its affecting.

sorry to be a bother lol

**Comment by TheIllusiveC4** [comment] 2022-02-09 02:02
If you've attached any screenshots, then I don't see anything. I don't think GitHub can receive screenshots attached in an email reply.

**Comment by Coraline77447** [comment] 2022-02-11 17:14
I'm having the same issue but with my personal modpack and I've done some testing and I can confirm that the latest version of Polymorph with the latest version of Sophisticated Backpacks aren't working together.
 
I had thought that Modern UI was causing this but I took out nearly all of the mods that I'm going to play with today but Polymorph and Sophisticated Backpacks and sure enough the game crashed with both of them installed. 

I'll provide the crash reports and logs. Yes, that's right, crash reports and logs since I had crashed the first time earlier today and during my final testing with the only two mods installed (Polymorph and Sophisticated Backpacks)

With Modern UI, Polymorph, and Sophisticated Backpacks along with the rest of my mods list;
https://pastebin.com/Tw1ehFtQ

Without Modern UI and the rest of my mods list, only Polymorph and Sophisticated Backpacks;
https://pastebin.com/akwBzC1m

Log from the first crash earlier today:
[2022-02-11-1.log](https://github.com/TheIllusiveC4/Polymorph/files/8050314/2022-02-11-1.log)

Latest log (from my final test with Polymorph and Sophisticated Backpacks installed);
[latest.log](https://github.com/TheIllusiveC4/Polymorph/files/8050308/latest.log)

**Comment by Coraline77447** [comment] 2022-02-11 17:14
Apparently your compat integration didn't go as planned, since one of the mixins that's responsible for compatibility integrations in Polymorph is failing to apply compatibility integrations with Sophisticated Backpacks.

But what's odd to me is the fact that yesterday both of these mods were working just fine in my mod list called Cora Tinkers for my modded singleplayer world with the same name but today they're not working in my mod list called Cora World 2 for my modded singleplayer world with the same name (I always name my personal mods lists aka personal modpacks after the worlds they're made for)...

One last thing, why I'm not making my own issue report about this is cause my report would've been too similar to this one cause of the information that Heroncustom provided already (minus their crash report(s) since they couldn't provide one cause their game wasn't providing one for some odd reason) which gives me enough evidence that makes my experience with this issue practically the same as theirs but not precisely the same however.
So why not have me write in the comments of this report with the helpful information that Heroncustom needed?
I'm practically helping Heroncustom, myself and you to find out what's causing this and resolve it for good.

**Comment by Heroncustom** [comment] 2022-02-11 17:26
I updated sophisticated backpacks to their beta version, polymorphs working
now.....

**Comment by Coraline77447** [comment] 2022-02-11 17:34
I am currently using their beta version... (sophisticatedbackpacks-1.18.1-3.15.9.533)

I'm gonna test out Polymorph 0.35 with the version of Sophisticated Backpacks it's bounded to instead if the beta version (hope it's not bound to that beta version of Sophisticated Backpacks). 
I'll report my findings cause their beta version isn't working for me with Polymorph 0.35 now even tho they were working for me previously... 
Like I've I'd said _"But what's odd to me is the fact that yesterday both of these mods were working just fine"_ but now they're not......

**Comment by Coraline77447** [comment] 2022-02-11 18:26
OMFG.... I'd just finally realized that I'm SOOOOOO dumb because my mod list (Cora Tinkers) that I was playing with yesterday has the latest version of Polymorph (0.37) but Cora World 2 mod list has 0.35 and I thought that I'd copied the latest version to Cora World 2 today but somehow I didn't even tho I thought that I did, so every single little thing that I've said earlier IS ALL FOR....nothing..........

Dreadfully sorry for all of that, didn't have any realization of what version of Polymorph that I was using and I clearly didn't read everything thoroughly since I didn't thoroughly read the versions that I'm trying to use because I distinctly remember switching out 0.35 for 0.37 from the mod list I was playing with yesterday....

So would you like me to delete all of my comments but this one or all of them or would you prefer to delete all of my comments like as if I was never here to interrupt with misleading information cause of my own stupidity........

Note to self, must keep all mod lists up-to date even when I'm not playing with a few of them for a few days or more.............

**Comment by TheIllusiveC4** [comment] 2022-02-11 22:24
It's alright, you can just leave it as it is. I'll be closing this issue as it seems the problem is solved as long as Polymorph and Sophisticated Backpacks are both updated.

**Closed as completed by TheIllusiveC4** 2022-02-11 22:24 UTC
Labels: type: bug
