### ISSUE TITLE
Item image not appearing in carfting output slot when using the autofill function of JEI

### ISSUE THREAD

**Issue by toktoktheeo** [TheIllusiveC4/Polymorph#54] opened 2021-01-17 01:57 UTC
Mod List:
  [✔️] additional_lights-1.16.4-2.1.3
  [✔️] AdiectaMateria2.4.1-1.16.4
  [✔️] Advancement_Book-1.16.4-1.0.4
  [✔️] AkashicTome-1.4-15
  [✔️] Aquaculture-1.16.4-2.1.12
  [✔️] Ashenwheat-1.16.4-4.4.1.0
  [✔️] AttributeFix-1.16.4-9.0.5
  [✔️] AutoRegLib-1.6-47
  [✔️] bettas-1.2.1
  [✔️] BetterAdvancements-1.16.4-0.1.0.103
  [✔️] BetterMineshafts-Forge-1.16.3-1.1.1
  [✔️] Bookshelf-1.16.4-9.3.25
  [✔️] Botania-1.16.4-410
  [✔️] BotanyPots-1.16.4-6.0.17
  [✔️] BotanyTrees-1.16.4-2.0.7
  [✔️] breesources-1.16.4-1.0.3.2
  [✔️] Buddycards-1.16.4-1.6.0
  [✔️] buildersaddition-1.16.4-20210113c
  [✔️] byg-1.1.7-BETA-v2
  [✔️] CalemiUtils-1.16.4-1.0.2
  [✔️] CannabisCraft1.16.4v4.1.5
  [✔️] carrotslib-mc1.16.4-3.0b1
  [✔️] Cazfps_lamps_1.16.4
  [✔️] champions-forge-1.16.4-2.0.0.2
  [✔️] chocolate-1.3.0-1.16.4
  [✔️] chunkloaders-1.1.3-mc1.16.4
  [✔️] cofh_core-1.16.3-1.1.6
  [✔️] collective-1.16.4-1.53
  [✔️] comforts-forge-1.16.4-4.0.1.0
  [✔️] CommonCapabilities-1.16.4-2.5.5
  [✔️] constructionwand-1.16.2-1.7
  [✔️] Controlling-7.0.0.11
  [✔️] CraftingCraft_1.16.3-9.2.0
  [✔️] craftingstation-4.1.1
  [✔️] CrockPot-1.16.3-1.3.3-release
  [✔️] crumbs-1.0.6+1.16.4-forge
  [✔️] Cucumber-1.16.4-4.1.5
  [✔️] culinaryconstruct-forge-1.16.4-4.0.0.2
  [✔️] curios-forge-1.16.4-4.0.3.5
  [✔️] CyclopsCore-1.16.4-1.9.5
  [✔️] decorative_blocks-1.16.4-1.7.2
  [✔️] decorative_winter-0.1.2
  [✔️] DeLogger-1.16.4-1.0.8+mc-1.16.4
  [✔️] DimStorage-1.16.4-4.3.0
  [✔️] Ding-1.16.3-1.2.0
  [✔️] dpanvil-1.16.3-1.0.3
  [✔️] DramaticDoors-1.16.3-1.1.0
  [✔️] eidolon-0.2.7
  [✔️] elementalcraft-1.16.4-2.5.1
  [✔️] elevatorid-1.16.4-1.7.10
  [✔️] embellishcraft-1.16.4-3.3.0.0
  [✔️] EnergeticSheep-1.16.4-1.1.7
  [✔️] exoticbirds-1.16.4-1.0.1
  [✔️] farlanders-1.16.4-1.3.7
  [✔️] FarmersDelight-1.16.3-0.2.4b
  [✔️] FarmingForBlockheads_1.16.3-7.2.1
  [✔️] ferritecore-1.1.1
  [✔️] Floocraft 1.16.3-1.15.2
  [✔️] FluxNetworks-1.16.4-6.1.5.10
  [✔️] FriendlyFire-1.16.4-6.0.1
  [✔️] gunswithoutroses-1.16.4-1.0.6
  [✔️] HarderFarther-1.16.2-1.61.0.5
  [✔️] HearthstoneMod-1.16.4-1.0.0
  [✔️] horse_colors-1.16.4-1.5.2
  [✔️] HQM-1.16.2+5.5.4-forge
  [✔️] Hwyla-forge-1.10.11-B78_1.16.2
  [✔️] improved-stations-2.0.1
  [✔️] IntegratedCrafting-1.16.4-1.0.11
  [✔️] IntegratedDynamics-1.16.4-1.2.0
  [✔️] IntegratedTerminals-1.16.4-1.1.1
  [✔️] IntegratedTunnels-1.16.4-1.6.15
  [✔️] itemcollectors-1.0.9-mc1.16.4
  [✔️] jei-1.16.4-7.6.1.65
  [✔️] jeiintegration_1.16.4-6.1.1.11
  [✔️] Jellyfishing-1.5.12
  [✔️] LotsMoreFood-1.16.4-1.2.0
  [✔️] magipsi-1.16.4-2.0.0.0
  [✔️] mapperbase-1.16.4-2.3.0.0
  [✔️] Masonry_Blocks_1.16.4_1.0
  [✔️] mcw-furniture-2.0.0-mc1.16.4
  [✔️] Mekanism-1.16.4-10.0.18.445
  [✔️] MekanismAdditions-1.16.4-10.0.18.445
  [✔️] MekanismGenerators-1.16.4-10.0.18.445
  [✔️] MekanismTools-1.16.4-10.0.18.445
  [✔️] mining-helmet-1.16.4-2.0.0
  [✔️] miraisoftloginmessages-1.16.2-1.16.4-1.0.2
  [✔️] mobcatcher-3.1
  [✔️] MoreJellyfish-1.1.2
  [✔️] Morpheus-1.16.4-4.2.68
  [✔️] MysticalAgradditions-1.16.4-4.1.3
  [✔️] MysticalAgriculture-1.16.4-4.1.4
  [✔️] mysticalworld-1.16.4-0.3.1.6
  [✔️] NaturesAura-33.4
  [✔️] NaturesCompass-1.16.4-1.8.6
  [✔️] occultism-1.0.4
  [✔️] OptiForge-MC1.16.4-0.4.6
  [✔️] packedup-1.0.21-mc1.16.4
  [✔️] pamhc2crops-1.16.3-1.0.1
  [✔️] pamhc2foodcore-1.16.3-1.0.0
  [✔️] pamhc2foodextended-1.16.3-1.0.0
  [✔️] pamhc2trees-1.16.3-1.0.0
  [✔️] Patchouli-1.16.4-48
  [✔️] petrevivemod-1.1
  [✔️] Placebo-1.16.3-4.3.3
  [✔️] pneumaticcraft-repressurized-1.16.4-2.9.2-116
  [✔️] polymorph-forge-1.16.4-0.22
  [✔️] preview_OptiFine_1.16.4_HD_U_G6_pre12
  [✔️] productivebees-1.16.4-0.5.2.9
  [✔️] Psi-1.16-90
  [✔️] QuarkOddities-1.16.3
  [✔️] Quark-r2.4-294
  [✔️] randompatches-2.1.5-forge
  [✔️] repurposed_structures-1.16.4-2.3.4
  [✔️] ResourcefulBees1.16.3-1.16.4-0.5.8b
  [✔️] Roads-1.16.2-1.1.0
  [✔️] rsgauges-1.16.4-1.2.7-b2
  [✔️] ServerTabInfo-1.16.4-1.3.3
  [✔️] SimplyHammers-1.16.4-1.3
  [✔️] skinned_lanterns-1.16.4-1.3.1
  [✔️] sleeping_bags-1.16.4-1.0.1
  [✔️] solpotato-1.16.4-1.0.7
  [✔️] SpawnerFix-1.16.2-1.0.0.2
  [✔️] stackrefill_1.16.4-1.1
  [✔️] storage_overhaul-1.16.4-1.0.3
  [✔️] structure_gel-1.16.4-1.7.4
  [✔️] supplementaries-0.9.20c
  [✔️] sworddisplay-1.16.2-1.1.2
  [✔️] tesseract-1.0.17-mc1.16.4
  [✔️] thermal_cultivation-1.16.3-1.1.6
  [✔️] thermal_expansion-1.16.3-1.1.6
  [✔️] thermal_foundation-1.16.3-1.1.6
  [✔️] thermal_innovation-1.16.3-1.1.7
  [✔️] thermal_locomotion-1.16.3-1.1.6
  [✔️] TheVeggieWay-1.16.4-2.2.12
  [✔️] Toast-Control-1.16.3-4.3.0
  [✔️] tombstone-1.16-6.2.4
  [✔️] trashcans-1.0.6a-mc1.16.4
  [✔️] TravelGates-1.0.6_1.16.4
  [✔️] usefulhats-1.9.3-1.16.2+
  [✔️] vanillacookbook-1.16.4-1.10
  [✔️] vanillafoodpantry-mc1.16.4-6.0b1
  [✔️] vanillathings-1.16.4-0.5
  [✔️] veinmining-forge-1.16.4-0.6
  [✔️] VillagersRespawn-1.16.4-1.16.4-1.35.0.3
  [✔️] WailaHarvestability-mc1.16.2-forge-1.1.13
  [✔️] Xaeros_Minimap_21.0.0_Forge_1.16.5
  [✔️] XaerosWorldMap_1.11.7_Forge_1.16.5
  [✔️] xptome-1.16.4-v2.0
#### Versions (Be specific, do not write "latest"):
* Polymorph: polymorph-forge-1.16.4-0.22
* Forge/Fabric: 35.1.36
#### Observed Behavior:
![2021-01-16_12 48 19](https://user-images.githubusercontent.com/34038708/104823119-ffa72b00-5847-11eb-8d6f-9ef25c3f8ca3.png)
![2021-01-16_12 48 30](https://user-images.githubusercontent.com/34038708/104823121-0170ee80-5848-11eb-9675-28f397bac78c.png)
![2021-01-16_12 48 45](https://user-images.githubusercontent.com/34038708/104823122-02098500-5848-11eb-88c3-fe7a449179e2.png)

When you are in the GUI of a crafting table or when you craft from your inventory (vanilla or modded) and you use JEI (the (+) button) to autofill a recipe, the output item image does not appear in the output slot. The output item is there, if you click on the output slot you get the item, but it only appears if you click in the output slot. It only happens when using the (+) JEI Button. When you put the ingredients manually in the crafting table the output items appears normally. It does not happen every time and when you take back one of the ingredients and put it back in the slot, the output appears normally.
Without polymorph installed, this bug doesn't happen.
#### Expected Behavior:
To see the output of the recipe in the output slot.
#### Steps to Reproduce:
1.Have the required ingredients of the recipe in your inventory while in the GUI of a crafting table.
2.Select a recipe in JEI.
3.Click on the (+) button under the recipe.
4.See the item placed in the crafting table but the output of the recipe does not appear in the output slot.
...

Have a nice day.

**Comment by TheIllusiveC4** [comment] 2021-01-17 05:01
After several attempts, I cannot reproduce this behavior.

Does this happen in single player, multiplayer, or both?
Does this happen with ONLY Polymorph installed?

**Comment by toktoktheeo** [comment] 2021-01-17 11:32
Hi,
I tried to find the culprit. It seems that the issue happens when Polymorph and Productive Bees are in the mod list. Without Productive Bees or without Polymorph, it does not happen. It does not happen with only Polymorph and it does not happen with only Polymorph and Productive Bees. It's very strange. It seems an other mod is conflicting in the mix. I'll continue testing to find out which mod is interacting. Thanks for your time. I'll update the issue if I manage to find the absolute minimum mix to make the issue happen every time.
I have not tried it in multiplayer. I'll test it that way.

**Comment by TheIllusiveC4** [comment] 2021-01-18 01:52
Don't worry about it too much if you can't isolate the issue further. After looking into this and another issue, this may be symptomatic of a deeper syncing issue within Polymorph and I plan to do some heavy refactors in an attempt to address it.

**Comment by TheIllusiveC4** [comment] 2021-11-04 01:09
I've rewritten the mod in such a way that this problem is either solved or completely different, so I'll be closing this issue. If something like this still occurs with version 0.26+, then please open a new bug report.

**Closed as completed by TheIllusiveC4** 2021-11-04 01:09 UTC
Labels: type: bug
