### ISSUE TITLE
Crashing on dedicated server

### ISSUE THREAD

**Issue by SirOMGitsYOU** [TheIllusiveC4/Polymorph#42] opened 2020-12-06 14:16 UTC
[crash-2020-12-06_14.06.49-fml.txt](https://github.com/TheIllusiveC4/Polymorph/files/5648877/crash-2020-12-06_14.06.49-fml.txt)

**Comment by TheIllusiveC4** [comment] 2020-12-07 00:03
Duplicate of #38
Update Polymorph.

**Closed as completed by TheIllusiveC4** 2020-12-07 00:03 UTC
Labels: type: bug
