### ISSUE TITLE
[Bug]: Server won't stop normally

### ISSUE THREAD

**Issue by Wolfy8198** [TheIllusiveC4/Polymorph#283] opened 2024-09-17 12:18 UTC
### Minecraft Version

1.20.1

### What happened?

I'm playing on 1.20.1 and was trying to make a new update for my modpack, Genesis Plus. For some reason after the world saves the server stops shutting down and just hangs. I spent 3 days trying to figure out what the issue was, before isolating Polymorph on the 3rd day. When I woke up on the 3rd day, I asked for help in a few mod discord servers I'm in, and found that a couple of people have been experiencing the same thing. For me, the issue happened with 0.49.6 but not 0.49.5. For another person it happened with 0.49.5.

### How do you trigger this bug?

1. Update Polymorph
2.
3.
...

### Loader

Fabric

### Loader Version

Fabric 0.16.5

### API Version

Fabric API 0.92.2

### Mod Version

Polymorph 0.49.6 1.20.1

### Relevant Log Outputs

https://pastebin.com/xNpxCwf6

**Comment by SharpIceX** [comment] 2024-09-17 12:23
I also encountered similar problems...

**Comment by TheIllusiveC4** [comment] 2024-09-18 00:36
I am unable to reproduce this. Starting a server with Polymorph 0.49.6 and Fabric API 0.92.2 on 1.20.1, I am able to `/stop` and the server shuts down normally.

Have either of you tested this with _just_ Polymorph installed? Also, I don't see anything referring to Polymorph in the log attached. Is this a situation where removing Polymorph from the instance fixes the issue? If so, this could be a case of a mod conflict with another mod and I'll need some more information to continue investigating.

**Comment by Wolfy8198** [comment] 2024-09-18 00:42
It was fixed when I changed my polymorph version from 0.49.6 to 0.49.5. I
have just under 300 mods in my modpack, so Polymorph is essential to it.
I'm sure it's not an issue with polymorph alone, but with my mods the
latest version breaks the server.

**Comment by TheIllusiveC4** [comment] 2024-09-18 01:11
The only change between 0.49.6 and 0.49.5 was an update to the configuration library, so it may be that another mod is somehow incompatible with that. Can you share the `latest.log` or `debug.log` file from the session where the server hangs?

**Comment by SharpIceX** [comment] 2024-09-18 01:20
> The only change between 0.49.6 and 0.49.5 was an update to the configuration library, so it may be that another mod is somehow incompatible with that. Can you share the `latest.log` or `debug.log` file from the session where the server hangs?

I strongly suspect it's a configuration-related issue, perhaps related to "night config"

**Comment by TheIllusiveC4** [comment] 2024-09-18 01:31
> perhaps related to "night config"

That's the configuration library that was updated so it's likely to be related to the cause. But I would need to see the `latest.log` or `debug.log` files from the sessions where the error occurs to check for any relevant stacktraces. Those files will also have a list of mods loaded that I can see.

**Comment by SharpIceX** [comment] 2024-09-18 01:45
> > perhaps related to "night config"
> 
> That's the configuration library that was updated so it's likely to be related to the cause. But I would need to see the `latest.log` or `debug.log` files from the sessions where the error occurs to check for any relevant stacktraces. Those files will also have a list of mods loaded that I can see.

In fact, even the trace level logs have no useful information. I will try to find out the mod conflict after I get off work (I am a FabricMC server with 300+ mods)

**Comment by SharpIceX** [comment] 2024-09-18 16:00
The following Mod combinations will cause the server to fail to shut down normally:

## 1. Fabric API, Create, Polymorph (Fabric 1.20.1 Server)

- [Fabric API 1.20.1 0.92.2+1.20.1](https://modrinth.com/mod/fabric-api/version/0.92.2+1.20.1)
- [Create Fabric 1.20.1 v0.5.1.f Patch 1](https://modrinth.com/mod/create-fabric/version/0.5.1-f-build.1417+mc1.20.1)
- [Polymorph Fabric 1.20.1 0.49.6](https://modrinth.com/mod/polymorph/version/57BJwR3V)

[thread_dump.txt](https://github.com/user-attachments/files/17047174/thread_dump.txt)

[latest.log](https://github.com/user-attachments/files/17047175/latest.log)


## 2. Fabric API, Framework, Forge Config API Port, Polymorph, GoblinTraders Fabric(Official version, not a third-party port) (Fabric 1.20.1 Server)

- [Fabric API 1.20.1 0.92.2+1.20.1](https://modrinth.com/mod/fabric-api/version/0.92.2+1.20.1)
- [Framework Fabric 1.20.1 0.7.8](https://www.curseforge.com/minecraft/mc-mods/framework/files/5692385)
- [Forge Config API Port Fabric 1.20.1 v8.0.0](https://modrinth.com/mod/forge-config-api-port/version/v8.0.0-1.20.1-Fabric)
- [Polymorph Fabric 1.20.1 0.49.6](https://modrinth.com/mod/polymorph/version/57BJwR3V)
- [GoblinTraders Fabric 1.20.1 1.9.3](https://www.curseforge.com/minecraft/mc-mods/goblintraders-fabric/files/4802504)

## 3. Fabric API, Forge Config API Port, Puzzles Lib, Straw Statues, Polymorph (Fabric 1.20.1 Server)

- [Fabric API 1.20.1 0.92.2+1.20.1](https://modrinth.com/mod/fabric-api/version/0.92.2+1.20.1)
- [Forge Config API Port Fabric 1.20.1 v8.0.0](https://modrinth.com/mod/forge-config-api-port/version/v8.0.0-1.20.1-Fabric)
- [Puzzles Lib Fabric 1.20.1 v8.1.23](https://modrinth.com/mod/puzzles-lib/version/v8.1.23-1.20.1-Fabric)
- [Straw Statues Fabric 1.20.1 v8.0.3](https://modrinth.com/mod/forge-config-api-port/version/v8.0.0-1.20.1-Fabric)
- [Polymorph Fabric 1.20.1 0.49.6](https://modrinth.com/mod/polymorph/version/57BJwR3V)

> [!NOTE]
> **I suspect 2 and 3 are caused by Forge Config API Port Mod.

**Comment by Wolfy8198** [comment] 2024-09-18 17:18
I see. In my case, it was the polymorph create combo

**Comment by TheIllusiveC4** [comment] 2024-09-19 03:28
Thank you, I'm able to reproduce the bug now. I'll be working on a solution and hopefully will have an update out soon.

**Comment by TheIllusiveC4** [comment] 2024-09-19 07:17
This should be fixed in Polymorph 0.49.7, although it's more of a workaround than a proper resolution.

It's definitely somehow caused by mods using two different versions of NightConfig (i.e one mod using 3.6.x and another mod using 3.8.x) but I'm not really sure why or what can be done about it. But it's important to note because this may very well occur with other combinations of mods without Polymorph involved. For my end, I just reverted the library back to a 3.6.x version for now.

**Closed as completed by TheIllusiveC4** 2024-09-19 07:17 UTC
Labels: type: bug, status: confirmed
