### ISSUE TITLE
[Feature]: compatiblity 1.19.2

### ISSUE THREAD

**Issue by hi4444** [TheIllusiveC4/Polymorph#243] opened 2023-10-24 14:08 UTC
### What is the new feature or improvement?

can you make it work with the crafting station mod by tfarecnim

**Comment by SGZ-Creations** [comment] 2024-03-05 21:55
I second this one
https://www.curseforge.com/minecraft/mc-mods/crafting-station

**Comment by TheIllusiveC4** [comment] 2024-03-27 04:38
Duplicate of https://github.com/illusivesoulworks/polymorph/issues/197

**Closed as not planned by TheIllusiveC4** 2024-03-27 04:38 UTC
Labels: duplicate, type: enhancement
