### ISSUE TITLE
[Bug]: Tom's Simple Storage Support 1.20.1

### ISSUE THREAD

**Issue by ArtanizAvi** [TheIllusiveC4/Polymorph#253] opened 2024-02-21 20:15 UTC
### Minecraft Version

1.20.1

### What happened?

When using Tom's Simple Storage Crafting Terminal, the Polymorph button does not appear for any of the recipes that it normally prompts. 

Polymorph still works correctly with out blocks like crafting table and furnace. 

Tom's Storage 1.20-1.6.5 is being used. 

### How do you trigger this bug?

1. Open Tom's crating terminal
2. Craft a recipe that has two outputs
3. No button appears to change output

### Loader

Fabric

### Loader Version

Fabric 0.15.6

### API Version

Fabric API 0.91.0+1.20.1

### Mod Version

0.49.1+1.20.1

**Comment by Cartrigger** [comment] 2024-03-01 23:43
Also happening here, kinda scuffed

**Comment by ffuentesm** [comment] 2024-03-02 06:16
Same problem here. 
It seems that all the supported crafting UIs are disabled in version 1.20.1
![image](https://github.com/illusivesoulworks/polymorph/assets/44974827/c68b96f4-718a-4e7f-9703-a8683aea8397)
And only the Vanilla inventoried are working
![image](https://github.com/illusivesoulworks/polymorph/assets/44974827/810cb5f8-b2a9-455a-a53f-54e23c3af709)

**Comment by TheIllusiveC4** [comment] 2024-03-27 04:34
Duplicate of https://github.com/illusivesoulworks/polymorph/issues/203

**Closed as not planned by TheIllusiveC4** 2024-03-27 04:34 UTC
Labels: type: bug, duplicate
