### ISSUE TITLE
incompatible with Oh the biomes you'll go!

### ISSUE THREAD

**Issue by NomSTee** [TheIllusiveC4/Polymorph#37] opened 2020-11-25 02:40 UTC
It is incompatible with byg crafting tables, the game is unable to boot up when these 2 mods are together.

**Comment by TheIllusiveC4** [comment] 2020-11-27 11:27
Duplicate of https://github.com/TheIllusiveC4/Polymorph/issues/36

**Closed as completed by TheIllusiveC4** 2020-11-27 11:27 UTC
Labels: type: bug
